### ISSUE TITLE
problem with introducing addons directory to multiserver

### ISSUE THREAD

**Issue by lostsoul6** [dasisdormax/cs2-multiserver#10]
Hello There ,

Without using multiserver , when you want to introduce /addons directory to cs2 , you edit a file called : gameinfo.gi and then add the following line to it : 

Game    csgo/addons/metamod

now with multiserver , the addons folder is placed in the following directory now : 

home/steam/msm.d/cs2/cfg/inst-public1/addons/metamod

but since the directory is completely different than game files , I don't know the correct syntax so that the game can recognize the new metamod directory .

Please see the picture below : 

![multiserver](https://github.com/dasisdormax/cs2-multiserver/assets/127633547/da26b0b6-8727-4397-8297-bc313bb48d33)

The first line is how I did it without multiserver running a single instance with steamcmd and the second line is what I'm trying to do now but I know this is not how to do it and I don't know how I should do it . 

Any help will be appreciated .

**Comment by dasisdormax** [comment]
Thanks for the report. 
I assume you are referring to this way of installing metamod: https://wiki.alliedmods.net/Installing_Metamod:Source#GameInfo

This does not work yet with the script and requires some work on my end. Each instance will need their own version of gameinfo.gi. I'll get back to you in a few days.

**Comment by lostsoul6** [comment]
@dasisdormax 

Yes it's very similar to the tutorial I used for installing metamod : 

https://www.ghostcap.com/how-to-install-cs2-plugins/

Thank you for taking the time to implement it . I will keep an eye on it .

**Comment by Haelnorr** [comment]
Hi, I am trying to implement a workaround by deleting the symlink for the gameinfo.gi, copying it from the base and editing the new copy with an updated path, but it still seems to be pulling the addon files from the base installation.

Doesn't solve the issue but hopefully is helpful with finding a solution.
![Screenshot_24](https://github.com/dasisdormax/cs2-multiserver/assets/16089714/24df0b31-5a00-4dc3-9f0a-0ac594434ada)

**Comment by lostsoul6** [comment]
@Haelnorr , developer will update us in a few days about that .

**Comment by dasisdormax** [comment]
> ..., but it still seems to be pulling the addon files from the base installation.

Yep, I noticed that one too. I got it fixed in the latest version by copying instead of symlinking some files.

After pulling the latest version, you'll need to re-create your instance with the following steps: (replace 'public1' with your instance names)

1. backup all files (logs, configs, ...) you may need from the instances.
2. delete the instance directories `rm -r ~/msm.d/cs2/inst-public1`. You can keep the config files.
3. create a new instance with `cs2-server @public1 create`

After that, you can install metamod:

1. Copy mmsource-x.x.x-linux.tar.gz to msm.d/cs2/inst-public1/game/csgo
2. `cd ~/msm.d/cs2/inst-public1/game/csgo`
3. `tar xzf mmsource-x.x.x-linux.tar.gz`
4. Edit game/csgo/gameinfo.gi to include `Game csgo/addons/metamod` above `Game csgo`.

That should do it. Good luck!

**Comment by lostsoul6** [comment]
@dasisdormax , did all the above but it still doesn't work and doesn't load addons . also after updating to new msm version , the game is laggy and I get this on console constantly :

[Prediction] CPrediction::PerformPrediction executed too many commands
[Prediction] CPrediction::PerformPrediction executed too many commands
[Prediction] CPrediction::PerformPrediction executed too many commands
[Prediction] CPrediction::PerformPrediction executed too many commands
[Prediction] CPrediction::PerformPrediction executed too many commands
[Prediction] CPrediction::PerformPrediction executed too many commands
[Prediction] CPrediction::PerformPrediction executed too many commands
[Prediction] CPrediction::PerformPrediction executed too many commands
[Prediction] CPrediction::PerformPrediction executed too many commands
[Prediction] CPrediction::PerformPrediction executed too many commands
[Prediction] CPrediction::PerformPrediction executed too many commands

**Comment by lostsoul6** [comment]
update : The above issue was solved and plugins work properly . what I did was to remove the cfg folders as well as the game files and create all of them again . everything is working as expected now .
